In [79]:
#import the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


#read the dataset
dataset = pd.read_csv("dengue.csv")

In [80]:
# Svm
# Decision tree
# Logistics regression
# Knn
# Random forest
# Neural network

In [81]:
#dsiplay the dataset
dataset.tail(300)

dengue.p_i_d dengue.date_of_fever dengue.residence dengue.days  \
495         P084               14-Jul          Karachi     6 days    
496         P082               13-May           Lahore      5 days   
497         P084               20-Mar        Islamabad     6 days    
498         P019               30-Nov           multan      8 days   
499          NaN                  NaN              NaN         NaN   
500          NaN                  NaN              NaN         NaN   
501          NaN                  NaN              NaN         NaN   
502          NaN                  NaN              NaN         NaN   
503          NaN                  NaN              NaN         NaN   
504          NaN                  NaN              NaN         NaN   
505          NaN                  NaN              NaN         NaN   
506          NaN                  NaN              NaN         NaN   
507          NaN                  NaN              NaN         NaN   
508          NaN                  NaN              NaN         NaN   
509          NaN                  NaN              NaN         NaN   
510          NaN                  NaN              NaN         NaN   
511          NaN                  NaN              NaN         NaN   
512          NaN                  NaN              NaN         NaN   
513          NaN                  NaN              NaN         NaN   
514          NaN                  NaN              NaN         NaN   
515          NaN                  NaN              NaN         NaN   
516          NaN                  NaN              NaN         NaN   
517          NaN                  NaN              NaN         NaN   
518          NaN                  NaN              NaN         NaN   
519          NaN                  NaN              NaN         NaN   
520          NaN                  NaN              NaN         NaN   
521          NaN                  NaN              NaN         NaN   
522          NaN                  NaN              NaN         NaN   
523          NaN                  NaN              NaN         NaN   
524          NaN                  NaN              NaN         NaN   
525          NaN                  NaN              NaN         NaN   
526          NaN                  NaN              NaN         NaN   
527          NaN                  NaN              NaN         NaN   
528          NaN                  NaN              NaN         NaN   
529          NaN                  NaN              NaN         NaN   
530          NaN                  NaN              NaN         NaN   
531          NaN                  NaN              NaN         NaN   
532          NaN                  NaN              NaN         NaN   
533          NaN                  NaN              NaN         NaN   
534          NaN                  NaN              NaN         NaN   
535          NaN                  NaN              NaN         NaN   
536          NaN                  NaN              NaN         NaN   
537          NaN                  NaN              NaN         NaN   
538          NaN                  NaN              NaN         NaN   
539          NaN                  NaN              NaN         NaN   
540          NaN                  NaN              NaN         NaN   
541          NaN                  NaN              NaN         NaN   
542          NaN                  NaN              NaN         NaN   
543          NaN                  NaN              NaN         NaN   
544          NaN                  NaN              NaN         NaN   
545          NaN                  NaN              NaN         NaN   
546          NaN                  NaN              NaN         NaN   
547          NaN                  NaN              NaN         NaN   
548          NaN                  NaN              NaN         NaN   
549          NaN                  NaN              NaN         NaN   
550          NaN                  NaN              NaN         NaN   
551          N

we can see that after 499 rows, rest are empty and null so we need to remove them.

In [82]:
#remove the null rows
newdata = dataset.drop(dataset.index[499:795], inplace=True)


In [83]:
dataset.tail(30)

dengue.p_i_d dengue.date_of_fever dengue.residence dengue.days  \
469         P019               10-Feb       Rawalpindi     9 days    
470         P091                9-Dec       Rawalpindi      3 days   
471         P061               18-Oct         Peshawar     2 weeks   
472         P077               25-Mar       Rawalpindi     10 days   
473         P066               29-Nov           Lahore      3 days   
474         P009               26-Jul         Peshawar      4 days   
475         P051               22-Mar           Quetta     2 weeks   
476         P071               26-Aug           Lahore     2 weeks   
477         P070               29-Mar        Islamabad   12 months   
478         P078               30-Jul       fasialabad        3--4   
479         P084               12-Aug             tank      5 days   
480         P091               11-Dec             swat   12 months   
481         P095               26-Oct           sakkar      1 days   
482         P005               23-Nov           Quetta     11 days   
483         P021               12-May           Quetta   12 months   
484         P003               10-May         Peshawar     2 weeks   
485         P097                7-May           sakkar        3--4   
486         P014               15-Oct             tank        3--4   
487         P069               26-Nov         Peshawar      5 days   
488         P003               23-Dec           Lahore   12 months   
489         P090                1-Mar             swat     10 days   
490         P073                2-Oct             tank     10 days   
491         P079                5-Aug            bannu     10 days   
492         P095               10-Dec       fasialabad     10 days   
493         P075               11-Oct        Islamabad      7 week   
494         P073               12-Mar          Karachi     6 days    
495         P084               14-Jul          Karachi     6 days    
496         P082               13-May           Lahore      5 days   
497         P084               20-Mar        Islamabad     6 days    
498         P019               30-Nov           multan      8 days   

     dengue.current_temp  dengue.wbc  dengue.servere_headche  \
469                 99.0         1.0                     0.0   
470                 98.0         2.0                     0.0   
471                  0.0         1.0                     0.0   
472                100.0         2.0                     1.0   
473                103.0         5.0                     1.0   
474                102.0         6.0                     1.0   
475                102.0         5.0                     1.0   
476                103.0         2.0                     1.0   
477                103.0         5.0                     1.0   
478                104.0         3.0                     1.0   
479                 99.0         4.0                     0.0   
480                103.0         3.0                     0.0   
481                103.5         4.0                     1.0   
482                102.5         3.0                     1.0   
483                 99.0         3.0                     1.0   
484                102.0         2.0                     0.0   
485                 99.0         3.0                     1.0   
486                100.0         3.0                     1.0   
487                101.0         3.0                     1.0   
488                104.0         4.0                     1.0   
489                102.0         4.0                     1.0   
490                104.0         2.0                     0.0   
491                105.0         2.0                     1.0   
492                 99.0         5.0                     1.0   
493                 98.0         4.0                     1.0   
494                100.0         3.0                     0.0   
495                 99.0         3.0                     1.0   
496                104.0         2.0     

In [84]:
#now lets find the nature and properties of data
print(len(dataset))

print(dataset.shape)

print(dataset.info())

print(dataset.isnull().sum())

499
(499, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 18 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   dengue.p_i_d                        499 non-null    object 
 1   dengue.date_of_fever                499 non-null    object 
 2   dengue.residence                    499 non-null    object 
 3   dengue.days                         499 non-null    object 
 4   dengue.current_temp                 498 non-null    float64
 5   dengue.wbc                          499 non-null    float64
 6   dengue.servere_headche              499 non-null    float64
 7   dengue.pain_behind_the_eyes         499 non-null    float64
 8   dengue.joint_muscle_aches           499 non-null    float64
 9   dengue.metallic_taste_in_the_mouth  499 non-null    float64
 10  dengue.appetite_loss                499 non-null    object 
 11  dengue.addominal_pain          

In [85]:
#find all the columns
dataset.columns

Index(['dengue.p_i_d', 'dengue.date_of_fever', 'dengue.residence',
       'dengue.days', 'dengue.current_temp', 'dengue.wbc',
       'dengue.servere_headche', 'dengue.pain_behind_the_eyes',
       'dengue.joint_muscle_aches', 'dengue.metallic_taste_in_the_mouth',
       'dengue.appetite_loss', 'dengue.addominal_pain',
       'dengue.nausea_vomiting', 'dengue.diarrhoea', 'dengue.hemoglobin',
       'dengue._hematocri', 'dengue.platelet', 'dengue.dengue'],
      dtype='object')

In the above description of the data we can see that there are not null values. Moreover, there are object values which we need to handle using one hot encoding.

In [86]:
#one hot encoding to handle the object values

dataset['dengue.p_i_d'].unique(), dataset['dengue.date_of_fever'].unique(), dataset['dengue.residence'].unique(), dataset['dengue.days'].unique()



(array(['P012', 'P011', 'P010', 'P009', 'P008', 'P007', 'P006', 'P005',
        'P100', 'P099', 'P098', 'P097', 'P096', 'P095', 'P094', 'P093',
        'P092', 'P091', 'P090', 'P089', 'P088', 'P087', 'P086', 'P085',
        'P084', 'P083', 'P082', 'P081', 'P080', 'P079', 'P078', 'P077',
        'P076', 'P075', 'P074', 'P073', 'P072', 'P071', 'P070', 'P069',
        'P068', 'P067', 'P066', 'P065', 'P064', 'P063', 'P062', 'P061',
        'P060', 'P059', 'P058', 'P057', 'P056', 'P055', 'P054', 'P053',
        'P052', 'P051', 'P050', 'P049', 'P048', 'P047', 'P046', 'P045',
        'P044', 'P043', 'P042', 'P041', 'P040', 'P039', 'P038', 'P037',
        'P036', 'P035', 'P034', 'P033', 'P032', 'P031', 'P030', 'P029',
        'P028', 'P027', 'P026', 'P025', 'P024', 'P023', 'P022', 'P021',
        'P020', 'P019', 'P018', 'P017', 'P016', 'P015', 'P014', 'P013',
        'P004', 'P003', 'P002', 'P001', ' P012'], dtype=object),
 array(['13-Jan', '13-Feb', '9-Jan', '12-Aug', '12-Oct', '10-Jun',
    

In [87]:
# we need to apply one hot encoding and columns will increase
oneHotEncoded_dataset = pd.get_dummies(dataset, columns = ['dengue.p_i_d', 'dengue.date_of_fever', 'dengue.residence', 'dengue.days'])
oneHotEncoded_dataset.head()

dengue.current_temp  dengue.wbc  dengue.servere_headche  \
0                100.0         5.0                     1.0   
1                104.0         1.0                     0.0   
2                104.0         5.0                     1.0   
3                101.0         2.0                     1.0   
4                101.0         5.0                     1.0   

   dengue.pain_behind_the_eyes  dengue.joint_muscle_aches  \
0                          1.0                        1.0   
1                          1.0                        1.0   
2                          0.0                        0.0   
3                          1.0                        1.0   
4                          1.0                        1.0   

   dengue.metallic_taste_in_the_mouth dengue.appetite_loss  \
0                                 0.0                    0   
1                                 1.0                    1   
2                                 1.0                    0   
3                                 0.0                    1   
4                                 1.0                    1   

   dengue.addominal_pain  dengue.nausea_vomiting  dengue.diarrhoea  ...  \
0                    1.0                     1.0               1.0  ...   
1                    1.0                     1.0               1.0  ...   
2                    0.0                     0.0               0.0  ...   
3                    1.0                     1.0               1.0  ...   
4                    1.0                     1.0               1.0  ...   

   dengue.days_12 months  dengue.days_2 weeks  dengue.days_3 days  \
0                      0                    0                   0   
1                      0                    0                   0   
2                      0                    0                   0   
3                      1                    0                   0   
4                      0                    0                   1   

   dengue.days_3--4  dengue.days_4 days  dengue.days_5 days  \
0                 0                   0                   0   
1                 0                   1                   0   
2                 0                   0                   1   
3                 0                   0                   0   
4                 0                   0                   0   

   dengue.days_6 days   dengue.days_7 week  dengue.days_8 days  \
0                    0                   0                   0   
1                    0                   0                   0   
2                    0                   0                   0   
3                    0                   0                   0   
4                    0                   0                   0   

   dengue.days_9 days   
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  

[5 rows x 375 columns]

In [88]:
#now again find the properties
print(len(oneHotEncoded_dataset))

print(oneHotEncoded_dataset.shape)

print(oneHotEncoded_dataset.info())

print(oneHotEncoded_dataset.isnull().sum())

499
(499, 375)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Columns: 375 entries, dengue.current_temp to dengue.days_9 days 
dtypes: float64(13), object(1), uint8(361)
memory usage: 230.6+ KB
None
dengue.current_temp                   1
dengue.wbc                            0
dengue.servere_headche                0
dengue.pain_behind_the_eyes           0
dengue.joint_muscle_aches             0
dengue.metallic_taste_in_the_mouth    0
dengue.appetite_loss                  0
dengue.addominal_pain                 0
dengue.nausea_vomiting                0
dengue.diarrhoea                      0
dengue.hemoglobin                     0
dengue._hematocri                     0
dengue.platelet                       0
dengue.dengue                         0
dengue.p_i_d_ P012                    0
dengue.p_i_d_P001                     0
dengue.p_i_d_P002                     0
dengue.p_i_d_P003                     0
dengue.p_i_d_P004                     0
dengue.p_i_d_P00

In [90]:
pd.set_option('display.max_rows', oneHotEncoded_dataset.shape[0]+1)
oneHotEncoded_dataset['dengue.current_temp']

0      100.0
1      104.0
2      104.0
3      101.0
4      101.0
5      104.0
6      104.0
7      103.5
8      103.0
9      101.0
10     105.0
11       0.0
12     100.0
13     104.0
14     104.0
15     101.0
16     101.0
17     104.0
18     104.0
19     103.5
20     103.0
21     101.0
22     105.0
23       0.0
24     100.0
25     104.0
26     104.0
27     101.0
28     101.0
29     104.0
30     104.0
31     103.5
32     103.0
33     101.0
34     105.0
35       0.0
36     100.0
37     104.0
38     104.0
39     101.0
40     101.0
41     104.0
42     104.0
43     103.5
44     103.0
45     101.0
46     105.0
47       0.0
48     100.0
49     104.0
50     104.0
51     101.0
52     101.0
53     104.0
54     104.0
55     103.5
56     103.0
57     101.0
58     105.0
59       0.0
60     100.0
61     104.0
62     104.0
63     101.0
64     101.0
65     104.0
66     104.0
67     103.5
68     103.0
69     101.0
70     105.0
71       0.0
72     100.0
73     104.0
74     104.0
75     101.0
76     101.0

In [91]:
oneHotEncoded_dataset['dengue.current_temp'].isnull().sum()

1

In [96]:
oneHotEncoded_dataset.drop(oneHotEncoded_dataset.index[324], inplace = True)

In [97]:
# values = {'dengue.current_temp': 0}

# oneHotEncoded_dataset['dengue.current_temp'].fillna(value=values)

In [98]:
oneHotEncoded_dataset['dengue.current_temp'].isnull().sum()

0

In [99]:
#split data into dependent and independent 
x = oneHotEncoded_dataset.iloc[:, :-1]
y = oneHotEncoded_dataset.iloc[:, -1]

In [100]:
x.shape

(497, 374)

In [101]:
y.shape

(497,)

In [102]:
#noe split the data into training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# SVM

In [103]:
#lets now apply SVM classifier and fit training data
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(x_train, y_train)

SVC()

In [104]:
#as we have fitted the model, now lets predict the model
predict = classifier.predict(x_test)

In [105]:
#lets find accuracy of model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, predict)
accuracy

0.99

In [106]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predict)
cm

array([[99,  0],
       [ 1,  0]], dtype=int64)

# Decision tree

In [107]:
from sklearn.tree import DecisionTreeClassifier
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)


In [113]:
#lets find accuracy of model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.98

In [114]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[98,  1],
       [ 1,  0]], dtype=int64)

# KNN

In [119]:
#now lets apply knn regressor
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(x_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [120]:
y_predict = knn.predict(x_test)

In [118]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predict)
cm

array([[99,  0],
       [ 1,  0]], dtype=int64)

# Logistics regression

In [125]:
# Import the library
from sklearn.linear_model import LogisticRegression

# Create the model
model = LogisticRegression()

# Train the model
model.fit(x_train, y_train)

# Predict using the model
y_pred0 = model.predict(x_test)


C:\Users\arfan.shah\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [126]:
#lets find accuracy of model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred0)
accuracy

0.99

In [127]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred0)
cm

array([[99,  0],
       [ 1,  0]], dtype=int64)

# Random Forest

In [122]:
# Import the library
from sklearn.ensemble import RandomForestClassifier

# Create the model
model = RandomForestClassifier()

# Train the model
model.fit(x_train, y_train)

# Predict using the model
y_pred1 = model.predict(x_test)

In [123]:
#lets find accuracy of model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred1)
accuracy

0.99

In [124]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred1)
cm

array([[99,  0],
       [ 1,  0]], dtype=int64)